apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: che-cluster
  namespace: devspaces
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  components:
    imagePuller:
      enable: true
      spec:
        images: >-
          kafka-native=quay.io/ogunalp/kafka-native@sha256:ac4deb7cc293c3e7880bcd9b8cdfbd83178c2023d473a9fb4fa7d154cb62dd14;kubedock=quay.io/agiertli/kubedock@sha256:8a20e4a95eaaf583427597aca1257dd5302a39e80dd7ab9ec7a2a407908c6a14;psql-14-martin=quay.io/xstefank/postgres@sha256:ec25e4bbfbaa7759c9ff844897cd15d2345c0bff6b3a5f84877e26a471999f77;psql-14=quay.io/agiertli/postgres@sha256:b85074605b3a5c7ddf547b056c37f466b4db7d11b0c877ee81de6c04219a5ac5;workshop-image=quay.io/agiertli/workshop-udi@sha256:a30632d511e022896c9a433c03c2b535696619fa18396a8e219ea567eacbea3e
    devWorkspace:
      runningLimit: '61'
    cheServer:
      debug: false
      logLevel: INFO
    metrics:
      enable: true
    pluginRegistry:
     openVSXURL: "https://open-vsx.org"
  containerRegistry: {}
  devEnvironments:
    disableContainerBuildCapabilities: false
    gatewayContainer:
      resources:
        limits:
          cpu: "4"
          memory: 5Gi
        request:
          cpu: "1"
          memory: 1Gi  
    secondsOfRunBeforeIdling: -1
    startTimeoutSeconds: 1200
    defaultNamespace:
      template: <username>-dev
    secondsOfInactivityBeforeIdling: -1
    storage:
      perWorkspaceStrategyPvcConfig:
        claimSize: 10Gi
      pvcStrategy: per-workspace
  networking: {}
