kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: customrole
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
rules:
  - verbs:
      - '*'
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
  - verbs:
      - '*'
    apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs      
      - builds
      - buildconfigs/instantiatebinary
      - builds/log
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments 
