apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: muse-glimmer
  namespace: muse-glimmer
spec:
  endpointOverride: https://maas.apps.ocp.b6ngg.sandbox1066.opentlc.com/muse-glimmer/muse-glimmer
  modelRef:
    kind: LLMInferenceService
    name: muse-glimmer
