apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: qwen3-8b
  namespace: rhoai-playground
spec:
  modelRef:
    kind: LLMInferenceService
    name: qwen3-8b
