apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: latest
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: openshift-pipelines-operator-rh