apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wolf-defender-model
  namespace: csob-sandbox
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
