apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    app: keycloak
  name: keycloak-http
  namespace: keycloak-system
spec:
  ports:
  - name: keycloak
    port: 8080
  selector:
    app: keycloak
    component: keycloak
