apiVersion: trustyai.opendatahub.io/v1
kind: EvalHub
metadata:
  name: evalhub
  namespace: csob-sandbox
spec:
  tenancy: single
  replicas: 1
  database:
    type: postgresql
    secret: evalhub-db-credentials
  providers:
    - garak
    - garak-kfp
  collections:
    - safety-and-fairness-v1
  env:
    - name: MLFLOW_TRACKING_URI
      value: "https://mlflow.redhat-ods-applications.svc.cluster.local:8443/mlflow"
