apiVersion: v1
kind: Secret
metadata:
  name: garak-s3-credentials
  namespace: csob-sandbox
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_S3_BUCKET: garak-pipeline
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_ENDPOINT: http://minio-service.minio.svc.cluster.local:9000
