apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: qwen3-5-35b-a3b
    serving.kserve.io/deploymentMode: RawDeployment
    security.opendatahub.io/enable-auth: "false"
  labels:
    opendatahub.io/dashboard: "true"
  name: qwen3-5-35b-a3b
  namespace: rhoai-playground
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - --dtype=float16
        - --max-model-len=8192
        - --gpu-memory-utilization=0.95
        - --enable-auto-tool-choice
        - --tool-call-parser=hermes
      modelFormat:
        name: vLLM
      resources:
        limits:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 16Gi
          nvidia.com/gpu: "1"
      runtime: qwen3-5-35b-a3b
      storageUri: oci://registry.redhat.io/rhai/modelcar-qwen3-5-35b-a3b-fp8-dynamic:3.0
