apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: qwen3-8b
    serving.kserve.io/deploymentMode: Standard
    security.opendatahub.io/enable-auth: "false"
  labels:
    opendatahub.io/dashboard: "true"
  name: qwen3-8b
  namespace: rhoai-playground
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - --dtype=float16
        - --max-model-len=16384
        - --gpu-memory-utilization=0.95
        - --enable-auto-tool-choice
        - --tool-call-parser=hermes
      modelFormat:
        name: vLLM
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 8Gi
          nvidia.com/gpu: "1"
      runtime: qwen3-8b
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-qwen3-8b-fp8-dynamic:1.5
