apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: amq
  name: example-clustered-broker
  namespace: amq
spec:
  acceptors:
    - expose: true
      exposeMode: route
      name: mqtt-acceptor
      port: 5672
      protocols: mqtt
  console:
    expose: true
  deploymentPlan:
    clustered: true
    image: placeholder
    journalType: nio
    messageMigration: true
    persistenceEnabled: true
    requireLogin: false
    size: 2
