apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: example-clustered-broker
spec:
  acceptors:
    - name: mqtt-acceptor
      exposeMode: route
      expose: true
      port: 5672
      protocols: mqtt
  console:
    expose: true
  deploymentPlan:
    size: 2
    image: placeholder
    requireLogin: false
    persistenceEnabled: true
    journalType: nio
    messageMigration: true
    clustered: true
