apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq
  namespace: amq
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: 7.13.x
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: amq-broker-rhel9
