apiVersion: v1
kind: Namespace
metadata:
  name: rhtas-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    kubernetes.io/metadata.name: rhtas-system
    argocd.argoproj.io/managed-by: openshift-gitops
