apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-4-12b-model
  namespace: csob-sandbox
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
