{{- range $key := .Values.users }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  labels:
    kubernetes.io/metadata.name: {{.name}}-dev
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-namespace    
  name: {{.name}}-dev
{{- end }}