{{- range $key := .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.name}}-admin-dev
  namespace: {{.name}}-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{.name}}
{{- end }}