apiVersion: v1
kind: Secret
metadata:
  name: s4-credentials
  namespace: {{ include "evalhub-infra.namespace" . }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s4.credentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s4.credentials.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.s4.credentials.region | quote }}
  AWS_S3_ENDPOINT: "http://{{ include "evalhub-infra.s4Host" . }}:7480"
  AWS_S3_BUCKET: {{ .Values.dspa.s3.bucket | quote }}
