apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s4-data
  namespace: {{ include "evalhub-infra.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.s4.pvc.size }}
